# 服务器
server:
  port: 8081

# 日志
logging:
  config: classpath:log4j2.xml

redis:
  host: 127.0.0.1
  port: 6379
  timeout: 60
  
spring:
# spring boot admin 监控 start
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # spring boot admin 监控 end

