send.mail: drkefu@daranair.com

# 服务器
server:
  port: 8888

spring:
  application:
      name: rome-admin-ui 
  mail: 
    port: 465
    host: smtp.daranair.com
    protocol: smtp
    username: ${send.mail}
    password: 1qaz@WSX
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true 
      mail.smtp.starttls: true
      mail.smtp.quitwait: false
  boot:
      admin:
        notify:
          mail:
            to: 549291615@qq.com # 通知到哪个邮箱




